# Übungsfragen {-}

1.  Was meint der Begriff Marktversagen'? Zeigen Sie auf, welche
    positiven und welche normativen Aussagen erforderlich sind, um ein
    Marktversagen festzustellen.

1.  Zeigen Sie anhand einer Edgeworth-Box die Menge der Tauschoptima!

1.  Zeigen Sie anhand einer Edgeworth-Box die Menge der
    Produktionsoptima!

1.  Reicht die getrennte Ermittlung von Tausch- und Produktionsoptima
    aus, um etwas über die Effizienz einer Volkswirtschaft auszusagen?

11.  Was sind soziale Wohlfahrtsfunktionen?

1.  Welche fünf Anforderungen stellt K. Arrow in seinem
    Unmöglichkeitstheorem' an die Aggregation individueller
    Wertvorstellungen zu einer Gesamtwertvorstellung? Welches Problem
    ergibt sich daraus?

1.  Was besagt die ,,Theorie des Zweitbesten"?

1. Was hingegen besagt die ,,Theorie des Drittbesten"?

1. Was ist ein natürliches Monopol? Nennen Sie Beispiele.

1. Welchen wirtschaftspolitischen Handlungsbedarf sehen Sie im
    Zusammenhang mit natürlichen Monopolen?

1. Welche Regulierungsstrategien kennen Sie im Zusammenhang mit
    natürlichen Monopolen? Wodurch zeichnen Sie sich jeweils aus?

1. Systematisieren Sie Güter anhand der Merkmale Rivalität und
    Ausschließbarkeit.

1. Welche wirtschaftspolitischen Probleme sehen Sie bei öffentlichen
    Gütern?

1. Wie ermittelt man die optimale Bereitstellungsmenge von öffentlichen
    Gütern in einer Volkswirtschaft?

1. Was sind ,,externe Effekte"? Welche Arten von externen Effekten gibt
    es?

1. Unterscheiden Sie negative von positiven externen Effekten. Führen
    beide zu Marktversagen?

1. Zeigen Sie den Wohlfahrtsverlust durch einen negativen externen
    Effekt anhand einer Grafik. Wovon hängt das Ausmaß des
    Wohlfahrtsverlustes ab?

1. Zeigen Sie den Wohlfahrtsverlust durch einen positiven externen
    Effekt anhand einer Grafik. Wovon hängt das Ausmaß des
    Wohlfahrtsverlustes ab?

1. Mit welchen wirtschaftspolitischen Instrumenten könnte man auf einen
    negativen externen Effekt reagieren? Nennen Sie jeweils Beispiele.

1. Zeigen Sie die Wirkung einer Pigou\" Steuer anhand einer geeigneten
    Grafik.

1. Mit welchen wirtschaftspolitischen Instrumenten könnte man auf einen
    positiven externen Effekt reagieren? Nennen Sie jeweils Beispiele.

1. Was sind adverse selection' und moral hazard'?

1. Führt die Abstimmung mit einfacher Mehrheit über eindimensionale
    Entscheidungsgegenstände stets zu einem eindeutigen und effizienten
    Ergebnis? Begründen Sie Ihre Antwort!

1. Erläutern Sie das Problem zyklischer Mehrheiten bei
    mehrdimensionalen Entscheidungssituationen (Abstimmung über die
    Bereitstellung zweier öffentlicher Güter)! Wodurch werden in realen
    Abstimmungssituationen Abstimmungsergebnisse typischerweise
    stabilisiert?

1. Zeigen Sie, dass bei Abstimmung mit einfacher Mehrheit eine andere
    kollektive Entscheidung resultieren kann als bei Abstimmung über die
    gleichen Alternativen nach dem Borda-Verfahren.

1. Welche von Arrows Anforderungen an Regeln kollektiver Entscheidungen
    kann das Borda-Wahlverfahren nicht erfüllen?


1. Warum ist selbst unter der Rationalitätsannahme nicht zu erwarten,
    dass Individuen permanent optimierende Entscheidungen treffen?

1. Erläutern Sie anhand einer geeigneten und kommentierten Grafik, wie
    im neoklassischen Standardmodell mit zwei Gütern das optimale
    Güterbündel ermittelt wird, wenn für eines der Güter ein sogenannter
    Flatrate\" Tarif gilt.

    Zeigen Sie hierbei zwei Fälle:

    1.  Im Vergleich eines normalen Tarifs und eines Flatratetarifs wird
        der normale Tarif (Abrechnung pro Einzeleinheit) bevorzugt.

    2.  Es wird der Flatratetarif bevorzugt.

1. Erläutern Sie, warum es plausibel sein könnte, dass Individuen einen
    Flatrate\" Tarif bevorzugen, obwohl im neoklassischen Standardmodell
    eine Einzelabrechnung einen höheren Nutzen verspricht.
